---
- name: clone dotfiles
  # personalized dotfiles are located on the m0rganic branch
  git: repo=http://github.com/m0rganic/dotfiles.git dest=/usr/share/dotfiles version=m0rganic
  sudo: yes
  tags: [git]

- name: link dotfiles
  file: dest=~/{{ item }} src=/usr/share/dotfiles/{{ item }} owner={{ user }} force=yes state=link
  tags: [copy]
  with_items:
    - .bashrc
    - .bash_profile
    - .gitconfig
    - .gitignore
    - .screenrc
    - .vimrc
    - .zshenv
    - .zshrc

- name: copy ssh_config
  file: dest=~/.ssh/config src=/usr/share/dotfiles/ssh_config state=link
  tags: [copy]


