---
- name: clone dotfiles
  # personalized dotfiles are located on the m0rganic branch
  git: repo=http://github.com/m0rganic/dotfiles.git dest=/tmp/dotfiles version=m0rganic
  sudo: yes
  tags: [git]

- name: copy dotfiles
  command: cp -f /tmp/dotfiles/{{ item }} ~/{{ item }}
  tags: [copy]
  with_items:
    - .bashrc
    - .bash_profile
    - .gitconfig
    - .gitignore
    - .screenrc
    # - .vimrc
    # - .zshenv
    # - .zshrc

- name: copy ssh_config
  command: cp -f /tmp/dotfiles/ssh_config ~/.ssh/config
  tags: [copy]


